"""add project detail columns

Revision ID: 90bce543df63
Revises: 
Create Date: 2026-02-27 16:23:05.909065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '90bce543df63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assumptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('assumption_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=100), nullable=False),
    sa.Column('affected_entities', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('impact_metrics', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('availability_start', sa.DateTime(), nullable=True),
    sa.Column('availability_end', sa.DateTime(), nullable=True),
    sa.Column('hourly_cost', sa.Float(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('allocation_status', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('duration_days', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('resource_requirements', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('trade_offs', sa.JSON(), nullable=True),
    sa.Column('lineage', sa.Enum('AI_GENERATED', 'HUMAN_CREATED', 'HYBRID', name='planlineagetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_duration_days', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('capacity_utilization', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('source_file_path', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('source_file_name', sa.String(length=255), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('UPLOADED', 'PARSING', 'GENERATING', 'COMPLETED', 'FAILED', name='planstatus'),
               nullable=False)
        batch_op.alter_column('lineage',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('AI_GENERATED', 'HUMAN_CREATED', 'HYBRID', name='planlineagetype'),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('tasks_json')
        batch_op.drop_column('explanation_json')
        batch_op.drop_column('constraints_json')
        batch_op.drop_column('recommendations_json')
        batch_op.drop_column('resources_json')
        batch_op.drop_column('assumptions_json')
        batch_op.drop_column('original_plan_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_type', sa.String(length=50), server_default='confirmed', nullable=False))
        batch_op.add_column(sa.Column('hull_length', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hull_width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hull_height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('topside_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('preferred_location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('preferred_yard', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('processes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('block_breakdown', sa.Text(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('block_breakdown')
        batch_op.drop_column('processes')
        batch_op.drop_column('preferred_yard')
        batch_op.drop_column('preferred_location')
        batch_op.drop_column('topside_weight')
        batch_op.drop_column('hull_height')
        batch_op.drop_column('hull_width')
        batch_op.drop_column('hull_length')
        batch_op.drop_column('project_type')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_plan_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('assumptions_json', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('resources_json', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('recommendations_json', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('constraints_json', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('explanation_json', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tasks_json', sqlite.JSON(), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('lineage',
               existing_type=sa.Enum('AI_GENERATED', 'HUMAN_CREATED', 'HYBRID', name='planlineagetype'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('UPLOADED', 'PARSING', 'GENERATING', 'COMPLETED', 'FAILED', name='planstatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('source_file_name')
        batch_op.drop_column('source_file_path')
        batch_op.drop_column('total_cost')
        batch_op.drop_column('capacity_utilization')
        batch_op.drop_column('total_duration_days')

    op.drop_table('tasks')
    op.drop_table('resources')
    op.drop_table('recommendations')
    op.drop_table('assumptions')
    # ### end Alembic commands ###
